export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',

  // Payment
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  PAYMENT_ALREADY_CONFIRMED = 'PAYMENT_ALREADY_CONFIRMED',
  MERCHANT_NOT_FOUND = 'MERCHANT_NOT_FOUND',

  // Blockchain
  BLOCKCHAIN_RPC_ERROR = 'BLOCKCHAIN_RPC_ERROR',
  BLOCKCHAIN_TRANSACTION_FAILED = 'BLOCKCHAIN_TRANSACTION_FAILED',
  BLOCKCHAIN_CONTRACT_ERROR = 'BLOCKCHAIN_CONTRACT_ERROR',

  // Auth
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  TWO_FACTOR_REQUIRED = 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_INVALID = 'TWO_FACTOR_INVALID',
  TWO_FACTOR_ALREADY_ENABLED = 'TWO_FACTOR_ALREADY_ENABLED',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  FORBIDDEN = 'FORBIDDEN',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Conversion
  CONVERSION_FAILED = 'CONVERSION_FAILED',
  PRICE_ORACLE_UNAVAILABLE = 'PRICE_ORACLE_UNAVAILABLE',

  // Cross-chain swaps
  SWAP_NOT_FOUND = 'SWAP_NOT_FOUND',
  SWAP_CHAIN_UNSUPPORTED = 'SWAP_CHAIN_UNSUPPORTED',
  SWAP_NOT_REFUNDABLE = 'SWAP_NOT_REFUNDABLE',
  SWAP_TIMELOCK_NOT_EXPIRED = 'SWAP_TIMELOCK_NOT_EXPIRED',
  SWAP_HASHLOCK_MISMATCH = 'SWAP_HASHLOCK_MISMATCH',
  SWAP_AMOUNT_MISMATCH = 'SWAP_AMOUNT_MISMATCH',

  // Notification
  WEBHOOK_NOT_FOUND = 'WEBHOOK_NOT_FOUND',
  WEBHOOK_DELIVERY_FAILED = 'WEBHOOK_DELIVERY_FAILED',
}
